### PR TITLE
Fixed #254

### LINKED ISSUE #254: UPDATE_APP_TO_LOGIN on execution.
I have this error after enter phone number:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/tg/__main__.py", line 78, in <module>
    main()
  File "/app/tg/__main__.py", line 69, in main
    tg.login()
  File "/usr/local/lib/python3.9/site-packages/telegram/client.py", line 574, in login
    self.authorization_state = self._wait_authorization_result(result)
  File "/usr/local/lib/python3.9/site-packages/telegram/client.py", line 504, in _wait_authorization_result
    result.wait(raise_exc=True)
  File "/usr/local/lib/python3.9/site-packages/telegram/utils.py", line 45, in wait
    raise RuntimeError(f'Telegram error: {self.error_info}')
RuntimeError: Telegram error: {'@type': 'error', 'code': 406, 'message': 'UPDATE_APP_TO_LOGIN', '@extra': {'request_id': 'updateAuthorizationState'}}
```

### PR DESCRIPTION
**Pull request by TruncatedDinosour**
#254

### CODE REVIEW

**Comment by TruncatedDinosour** [comment]
btw merging this will require some code changes in the way you handle updates and stuff so a thing to keep in mind 👍

**Comment by CaramelHeaven** [comment]
Can we merge it ? 5 days have already passed

**Comment by TruncatedDinosour** [comment]
> btw **merging this will require some code changes** in the way you handle updates and stuff so a thing to keep in mind 👍

If you merge this the code changes that should work are kinda here: https://github.com/TruncatedDinosour/arigram/commit/94ce9fe73c7627c33fa7d7fa38c13ee88e90d81a

**Comment by TruncatedDinosour** [comment]
https://github.com/paul-nameless/tg/issues/254#issuecomment-987284479

maybe this will work?

**Comment by TruncatedDinosour** [comment]
> [#254 (comment)](https://github.com/paul-nameless/tg/issues/254#issuecomment-987284479)
> 
> maybe this will work?

the AUR package is updated to 0.15.0 apperantly, though can't test it as I'm on gentoo, if anyone is on arch try installing it through the AUR

**Comment by CaramelHeaven** [comment]
Okay, it's work on macOS.

**Comment by z8512** [comment]
Thank you for letting us know about arigram. Gonna install it instead.  Tired of tg buga

**Comment by paul-nameless** [comment]
Thanks for PR, released new version already

**Pull request closed without merging**
