### PR TITLE
add setup.py

### PR DESCRIPTION
**Pull request by lightme16**
- use setuptool instead of flit to remove `flit` as extra dependency during packaging

### CODE REVIEW

**Comment by paul-nameless** [comment]
Let's keep flit in pyproject until or if we will move to some other tool for publishing package to pypi

**Comment by lightme16** [comment]
@paul-nameless we can use twine to upload to pypi, [see](https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives)

**Comment by paul-nameless** [comment]
Make sure content type is set
https://test.pypi.org/help/#description-content-type

I will test the upload through twine and remove flit from pyproject myself when it will work, so let's keep it for now.

**Comment by lightme16** [comment]
@paul-nameless ok

**Pull request merged**
