### PR TITLE
Edit messages inside the interface

### PR DESCRIPTION
**Pull request by ArthurBais**
'e' now edits messages in the program. 'E' opens it in an external editor.

### CODE REVIEW

**Comment by lightme16** [comment]
Hello, thanks for your PR. I like your idea, but have suggestion how to improve it.
In this PR `e` does msg rewrite, instead of actual message edit. So, let's display old message in status panel and allow user to edit it without retyping. You can use this patch to achieve it:

```
diff --git a/tg/controllers.py b/tg/controllers.py
index 9cc481f..5decc80 100644
--- a/tg/controllers.py
+++ b/tg/controllers.py
@@ -442,7 +442,7 @@ class Controller:
         if not msg.can_be_edited:
             return self.present_error("Message can't be edited!")
 
-        if text := self.view.status.get_input():
+        if text := self.view.status.get_input(msg.text_content):
             self.model.edit_message(text=text)
             self.present_info("Message edited")
         else:
@@ -459,7 +459,6 @@ class Controller:
         if not msg.can_be_edited:
             return self.present_error("Message can't be edited!")
 
-
         with NamedTemporaryFile("r+", suffix=".txt") as f, suspend(
             self.view
         ) as s:
diff --git a/tg/views.py b/tg/views.py
index da50386..b457df1 100644
--- a/tg/views.py
+++ b/tg/views.py
@@ -105,14 +105,18 @@ class StatusView:
         self.win.addstr(0, 0, msg.replace("\n", " ")[: self.w])
         self._refresh()
 
-    def get_input(self, msg: str = "") -> str:
-        self.draw(msg)
+    def get_input(self, buff: str = "") -> str:
+        self.draw(buff)
         curses.curs_set(1)
 
-        buff = ""
         while True:
-            key = self.win.get_wch(0, min(len(buff) + len(msg), self.w - 1))
+            self.win.erase()
+            line = buff[-(self.w - 1) :]
+            self.win.addstr(0, 0, line)
+
+            key = self.win.get_wch(0, min(len(buff), self.w - 1))
             key = ord(key)
+
             if key == 10:  # return
                 break
             elif key == 127:  # del
@@ -123,9 +127,6 @@ class StatusView:
                 break
             elif chr(key).isprintable():
                 buff += chr(key)
-            self.win.erase()
-            line = (msg + buff)[-(self.w - 1) :]
-            self.win.addstr(0, 0, line)
 
         self.win.clear()
         curses.curs_set(0)
```

Also, plz pay attention to the CI checks, they are red now. You can find CI command here https://github.com/paul-nameless/tg/blob/master/.github/workflows/main.yml#L39-L47

**Comment by ArthurBais** [comment]
Problem is that I can't get at least arrow keys to work to navigate the cursor while editing.

**Comment by paul-nameless** [comment]
Good point, we haven't implemented it yet. So maybe we should wait while this part will be implemented. I can do it in nearest future.

**Comment by paul-nameless** [comment]
Closing for now

**Pull request closed without merging**
