### PR TITLE
Change AUR package to version following releases

### PR DESCRIPTION
**Pull request by jugendhacker**
* Change from telegram-tg-git to telegram-tg

* Add hint for developement version (telegram-tg-git)

### CODE REVIEW

**Comment by lightme16** [comment]
Looks great, however let's wait for https://github.com/paul-nameless/tg/pull/155 merge. After that we can drop `dephell` support from both AURs.

**Comment by lightme16** [comment]
@jugendhacker I've added setup.py. So, you should be able to stop using `dephell` in both AURs. Could you plz check it out?

**Comment by jugendhacker** [comment]
@lightme16 I removed dephell from the -git package now, for the one following the releases I need to wait for the next release of course

**Comment by lightme16** [comment]
Ok. cool, thanks!

**Comment by paul-nameless** [comment]
Thanks for the patch! Release will be today-tomorrow.

**Pull request merged**
